export const STACK_MAP = {
  // Backend stacks
  laravel: {
    base: 'php:{v}-fpm-alpine',
    scaffold: 'composer create-project laravel/laravel {path}',
    scaffold_image: 'composer:latest',
    entry_point: 'public/index.php',
    language: { name: 'php', version: '8.3' },
    build_command: 'composer install',
    dev_command: 'php artisan serve',
    test_command: 'php artisan test',
    lint_command: 'vendor/bin/pint',
  },
  symfony: {
    base: 'php:{v}-fpm-alpine',
    scaffold: 'composer create-project symfony/skeleton {path}',
    scaffold_image: 'composer:latest',
    entry_point: 'public/index.php',
    language: { name: 'php', version: '8.3' },
    build_command: 'composer install',
    dev_command: 'symfony server:start',
    test_command: 'php bin/phpunit',
    lint_command: 'vendor/bin/php-cs-fixer fix --dry-run',
  },
  django: {
    base: 'python:{v}-slim',
    scaffold: 'django-admin startproject {name} {path}',
    scaffold_image: 'python:{v}-slim',
    entry_point: 'manage.py',
    language: { name: 'python', version: '3.12' },
    build_command: 'pip install -r requirements.txt',
    dev_command: 'python manage.py runserver 0.0.0.0:8000',
    test_command: 'python manage.py test',
    lint_command: 'ruff check .',
  },
  fastapi: {
    base: 'python:{v}-slim',
    scaffold: 'pip install fastapi uvicorn',
    scaffold_image: 'python:{v}-slim',
    entry_point: 'main.py',
    language: { name: 'python', version: '3.12' },
    build_command: 'pip install -r requirements.txt',
    dev_command: 'uvicorn main:app --host 0.0.0.0 --reload',
    test_command: 'pytest',
    lint_command: 'ruff check .',
  },
  express: {
    base: 'node:{v}-alpine',
    scaffold: 'npx express-generator {path}',
    scaffold_image: 'node:{v}-alpine',
    entry_point: 'src/index.js',
    language: { name: 'javascript', version: '20' },
    build_command: 'npm install',
    dev_command: 'npm run dev',
    test_command: 'npm test',
    lint_command: 'npm run lint',
  },
  nestjs: {
    base: 'node:{v}-alpine',
    scaffold: 'npx @nestjs/cli new {path}',
    scaffold_image: 'node:{v}-alpine',
    entry_point: 'src/main.ts',
    language: { name: 'typescript', version: '20' },
    build_command: 'npm install',
    dev_command: 'npm run start:dev',
    test_command: 'npm run test',
    lint_command: 'npm run lint',
  },
  'spring-boot': {
    base: 'eclipse-temurin:{v}-jdk',
    scaffold: 'spring init --dependencies=web,data-jpa --type=maven-project {path}',
    scaffold_image: 'eclipse-temurin:{v}-jdk',
    entry_point: 'auto-detect',
    language: { name: 'java', version: '21' },
    build_command: './mvnw install',
    dev_command: './mvnw spring-boot:run',
    test_command: './mvnw test',
    lint_command: './mvnw checkstyle:check',
  },
  dotnet: {
    base: 'mcr.microsoft.com/dotnet/sdk:{v}',
    scaffold: 'dotnet new webapi -o {path}',
    scaffold_image: 'mcr.microsoft.com/dotnet/sdk:{v}',
    entry_point: 'Program.cs',
    language: { name: 'csharp', version: '8.0' },
    build_command: 'dotnet restore',
    dev_command: 'dotnet watch run',
    test_command: 'dotnet test',
    lint_command: 'dotnet format --verify-no-changes',
  },
  // Frontend stacks
  react: {
    base: 'node:{v}-alpine',
    scaffold: 'npx create-vite {path} --template react-ts',
    scaffold_image: 'node:{v}-alpine',
    language: { name: 'typescript', version: '5.5' },
    build_command: 'npm run build',
    dev_command: 'npm run dev',
    test_command: 'npm run test',
    lint_command: 'npm run lint',
  },
  vue: {
    base: 'node:{v}-alpine',
    scaffold: 'npx create-vue {path}',
    scaffold_image: 'node:{v}-alpine',
    language: { name: 'typescript', version: '5.5' },
    build_command: 'npm run build',
    dev_command: 'npm run dev',
    test_command: 'npm run test',
    lint_command: 'npm run lint',
  },
  angular: {
    base: 'node:{v}-alpine',
    scaffold: 'npx @angular/cli new {path}',
    scaffold_image: 'node:{v}-alpine',
    language: { name: 'typescript', version: '5.5' },
    build_command: 'npm run build',
    dev_command: 'ng serve',
    test_command: 'ng test',
    lint_command: 'ng lint',
  },
  nextjs: {
    base: 'node:{v}-alpine',
    scaffold: 'npx create-next-app {path} --typescript',
    scaffold_image: 'node:{v}-alpine',
    language: { name: 'typescript', version: '5.5' },
    build_command: 'npm run build',
    dev_command: 'npm run dev',
    test_command: 'npm run test',
    lint_command: 'npm run lint',
  },
  nuxtjs: {
    base: 'node:{v}-alpine',
    scaffold: 'npx nuxi init {path}',
    scaffold_image: 'node:{v}-alpine',
    language: { name: 'typescript', version: '5.5' },
    build_command: 'npm run build',
    dev_command: 'npm run dev',
    test_command: 'npm run test',
    lint_command: 'npm run lint',
  },
  svelte: {
    base: 'node:{v}-alpine',
    scaffold: 'npx create-svelte {path}',
    scaffold_image: 'node:{v}-alpine',
    language: { name: 'typescript', version: '5.5' },
    build_command: 'npm run build',
    dev_command: 'npm run dev',
    test_command: 'npm run test',
    lint_command: 'npm run lint',
  },
};

export function getStackDefaults(stack, version) {
  const entry = STACK_MAP[stack];
  if (!entry) return null;

  const v = version || entry.language.version;
  return {
    ...entry,
    base: entry.base.replace('{v}', v),
    scaffold: entry.scaffold.replace('{v}', v),
    scaffold_image: entry.scaffold_image.replace('{v}', v),
  };
}
